"""initial schema

Revision ID: b90005e228cb
Revises: 
Create Date: 2026-10-02 18:34:02.447737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b90005e228cb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_health',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exchange', sa.String(length=100), nullable=False),
    sa.Column('is_healthy', sa.Boolean(), nullable=True),
    sa.Column('latency_ms', sa.String(length=20), nullable=True),
    sa.Column('last_check', sa.DateTime(timezone=True), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('arbitrage_opportunities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('buy_exchange_id', sa.UUID(), nullable=False),
    sa.Column('sell_exchange_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('buy_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('sell_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('gross_spread', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('gross_spread_percent', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('buy_fee', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('sell_fee', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('estimated_slippage', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('network_cost', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('other_costs', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('gross_profit', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('net_profit', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('net_profit_percent', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('status', sa.Enum('DETECTED', 'EXECUTABLE', 'REJECTED', 'EXECUTED', 'EXPIRED', name='opportunitystatus'), nullable=True),
    sa.Column('rejection_reason', sa.Enum('INSUFFICIENT_LIQUIDITY', 'STALE_MARKET_DATA', 'SPREAD_TOO_SMALL', 'FEES_TOO_HIGH', 'SLIPPAGE_TOO_HIGH', 'MIN_ORDER_NOT_MET', 'RISK_LIMIT_REACHED', 'DAILY_LOSS_LIMIT', 'EXCHANGE_UNAVAILABLE', 'ORDER_BOOK_CHANGED', 'CAPITAL_INSUFFICIENT', 'UNKNOWN_ORDER_STATE', 'NET_PROFIT_BELOW_THRESHOLD', 'KILL_SWITCH_ACTIVE', name='rejectionreason'), nullable=True),
    sa.Column('rejection_details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trade_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backtest_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='backteststatus'), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('initial_capital', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('final_capital', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('gross_profit', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('total_fees', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('total_slippage', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('net_profit', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('total_trades', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('winning_trades', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('losing_trades', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('profit_factor', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('avg_trade', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('largest_win', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('largest_loss', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('config_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_performance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('starting_capital', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('ending_capital', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('pnl', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('pnl_percent', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('trades_executed', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('winning_trades', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('losing_trades', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('total_fees', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('total_slippage', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('opportunities_detected', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('opportunities_rejected', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('exchanges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('api_base_url', sa.String(length=500), nullable=False),
    sa.Column('ws_url', sa.String(length=500), nullable=True),
    sa.Column('supports_spot', sa.Boolean(), nullable=True),
    sa.Column('supports_futures', sa.Boolean(), nullable=True),
    sa.Column('fee_maker', sa.String(length=20), nullable=True),
    sa.Column('fee_taker', sa.String(length=20), nullable=True),
    sa.Column('config_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('risk_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('DAILY_LOSS_LIMIT', 'TRADE_SIZE_LIMIT', 'MAX_OPEN_TRADES', 'MAX_TRADES_PER_DAY', 'STALE_DATA', 'EXCHANGE_UNAVAILABLE', 'KILL_SWITCH', 'UNKNOWN_ORDER_STATE', 'CAPITAL_INSUFFICIENT', name='riskeventtype'), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trade_id', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('asset', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('buy_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('sell_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('fees', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('gross_profit', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('net_profit', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('exchange', sa.String(length=100), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('jurisdiction', sa.String(length=100), nullable=True),
    sa.Column('tax_year', sa.String(length=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('mode', sa.Enum('SCANNER', 'PAPER', 'LIVE', name='trademode'), nullable=False),
    sa.Column('buy_exchange', sa.String(length=100), nullable=False),
    sa.Column('sell_exchange', sa.String(length=100), nullable=False),
    sa.Column('buy_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('sell_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('buy_fee', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('sell_fee', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('slippage', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('network_cost', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('gross_profit', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('net_profit', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'FILLED', 'PARTIALLY_FILLED', 'CANCELLED', 'FAILED', 'REJECTED', name='tradestatus'), nullable=True),
    sa.Column('buy_order_id', sa.String(length=100), nullable=True),
    sa.Column('sell_order_id', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('backtest_trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('backtest_run_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('buy_exchange', sa.String(length=100), nullable=False),
    sa.Column('sell_exchange', sa.String(length=100), nullable=False),
    sa.Column('buy_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('sell_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('buy_fee', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('sell_fee', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('slippage', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('gross_profit', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('net_profit', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exchange_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('bid', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('ask', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('bid_quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('ask_quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('last_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sequence_number', sa.BigInteger(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_snapshots_symbol'), 'market_snapshots', ['symbol'], unique=False)
    op.create_table('order_book_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exchange_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('bids_json', sa.String(length=10000), nullable=False),
    sa.Column('asks_json', sa.String(length=10000), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_book_snapshots_symbol'), 'order_book_snapshots', ['symbol'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trade_id', sa.UUID(), nullable=False),
    sa.Column('exchange', sa.String(length=100), nullable=False),
    sa.Column('exchange_order_id', sa.String(length=100), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='orderside'), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('filled_quantity', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('fee', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'FILLED', 'PARTIALLY_FILLED', 'CANCELLED', 'FAILED', 'REJECTED', name='tradestatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('initial_capital', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('current_capital', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('total_pnl', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('total_trades', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('winning_trades', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('losing_trades', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trading_pairs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exchange_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('base_asset', sa.String(length=10), nullable=False),
    sa.Column('quote_asset', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('min_order_size', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('max_order_size', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('tick_size', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('lot_size', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('balances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('asset', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('locked_quantity', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # Foreign keys are added after every table exists because
    # arbitrage_opportunities and trades reference each other.
    op.create_foreign_key('fk_arbitrage_opportunities_buy_exchange_id', 'arbitrage_opportunities', 'exchanges', ['buy_exchange_id'], ['id'])
    op.create_foreign_key('fk_arbitrage_opportunities_sell_exchange_id', 'arbitrage_opportunities', 'exchanges', ['sell_exchange_id'], ['id'])
    op.create_foreign_key('fk_arbitrage_opportunities_trade_id', 'arbitrage_opportunities', 'trades', ['trade_id'], ['id'])
    op.create_foreign_key('fk_trades_opportunity_id', 'trades', 'arbitrage_opportunities', ['opportunity_id'], ['id'])
    op.create_foreign_key('fk_trades_user_id', 'trades', 'users', ['user_id'], ['id'])
    op.create_foreign_key('fk_orders_trade_id', 'orders', 'trades', ['trade_id'], ['id'])
    op.create_foreign_key('fk_backtest_trades_backtest_run_id', 'backtest_trades', 'backtest_runs', ['backtest_run_id'], ['id'])
    op.create_foreign_key('fk_market_snapshots_exchange_id', 'market_snapshots', 'exchanges', ['exchange_id'], ['id'])
    op.create_foreign_key('fk_order_book_snapshots_exchange_id', 'order_book_snapshots', 'exchanges', ['exchange_id'], ['id'])
    op.create_foreign_key('fk_trading_pairs_exchange_id', 'trading_pairs', 'exchanges', ['exchange_id'], ['id'])
    op.create_foreign_key('fk_portfolios_user_id', 'portfolios', 'users', ['user_id'], ['id'])
    op.create_foreign_key('fk_balances_portfolio_id', 'balances', 'portfolios', ['portfolio_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_balances_portfolio_id', 'balances', type_='foreignkey')
    op.drop_constraint('fk_portfolios_user_id', 'portfolios', type_='foreignkey')
    op.drop_constraint('fk_trading_pairs_exchange_id', 'trading_pairs', type_='foreignkey')
    op.drop_constraint('fk_order_book_snapshots_exchange_id', 'order_book_snapshots', type_='foreignkey')
    op.drop_constraint('fk_market_snapshots_exchange_id', 'market_snapshots', type_='foreignkey')
    op.drop_constraint('fk_backtest_trades_backtest_run_id', 'backtest_trades', type_='foreignkey')
    op.drop_constraint('fk_orders_trade_id', 'orders', type_='foreignkey')
    op.drop_constraint('fk_trades_user_id', 'trades', type_='foreignkey')
    op.drop_constraint('fk_trades_opportunity_id', 'trades', type_='foreignkey')
    op.drop_constraint('fk_arbitrage_opportunities_trade_id', 'arbitrage_opportunities', type_='foreignkey')
    op.drop_constraint('fk_arbitrage_opportunities_sell_exchange_id', 'arbitrage_opportunities', type_='foreignkey')
    op.drop_constraint('fk_arbitrage_opportunities_buy_exchange_id', 'arbitrage_opportunities', type_='foreignkey')
    op.drop_table('balances')
    op.drop_table('trading_pairs')
    op.drop_table('portfolios')
    op.drop_table('orders')
    op.drop_index(op.f('ix_order_book_snapshots_symbol'), table_name='order_book_snapshots')
    op.drop_table('order_book_snapshots')
    op.drop_index(op.f('ix_market_snapshots_symbol'), table_name='market_snapshots')
    op.drop_table('market_snapshots')
    op.drop_table('backtest_trades')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('trades')
    op.drop_table('tax_records')
    op.drop_table('system_events')
    op.drop_table('risk_events')
    op.drop_table('exchanges')
    op.drop_table('daily_performance')
    op.drop_table('backtest_runs')
    op.drop_table('arbitrage_opportunities')
    op.drop_table('api_health')
    for _enum in (
        'opportunitystatus', 'rejectionreason', 'backteststatus', 'riskeventtype',
        'trademode', 'tradestatus', 'orderside',
    ):
        op.execute(sa.text(f'DROP TYPE IF EXISTS {_enum}'))
    # ### end Alembic commands ###
